"""Initial tables

Revision ID: c74fc30d550f
Revises: 
Create Date: 2026-02-03 23:42:53.371812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c74fc30d550f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certa_test_executions',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('requested_roles', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('ACQUIRING', 'RUNNING', 'COMPLETED', 'FAILED', name='testexecutionstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('acquired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('certa_users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('tenant', sa.Text(), nullable=True),
    sa.Column('domain', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('is_healthy', sa.Boolean(), nullable=False),
    sa.Column('locked_by', sa.String(length=255), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_certa_users_id'), 'certa_users', ['id'], unique=False)
    op.create_index(op.f('ix_certa_users_is_locked'), 'certa_users', ['is_locked'], unique=False)
    op.create_index(op.f('ix_certa_users_role'), 'certa_users', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_certa_users_role'), table_name='certa_users')
    op.drop_index(op.f('ix_certa_users_is_locked'), table_name='certa_users')
    op.drop_index(op.f('ix_certa_users_id'), table_name='certa_users')
    op.drop_table('certa_users')
    op.drop_table('certa_test_executions')
    # ### end Alembic commands ###
